language: python
matrix:
  include:
  - name: "3.6 Unit Test"
    python: "3.6"
  - name: "3.7 Unit Test"
    sudo: required
    dist: xenial
    python: "3.7"
branches:
  only:
    - master
install:
  - pip install python-coveralls
  - pip install -r requirements.txt
script:
  - python setup.py install
  - nosetests --with-coverage --cover-branches --cover-package=nanonispy
after_success: coveralls
