language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
- pip install python-coveralls
- pip install -r requirements.txt
script:
- python setup.py install
- nosetests --with-coverage --cover-branches --cover-package=nanonispy
after_success: coveralls
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: hya0ryCd6F/FPYiZzaqeR4uPJo39YEbRDL3918mJJt4isWsUg5itb/s9VC4UPKXULzIWN8gxno4mdqRAcTvMtoLUaUrpCjb/02Wt4Rg5Brfa/XWgxu6bRREJRH3gWvwIIFKNk9NTI8l2Chm+dCREUOSalct86E+Zceol19NwAVyofFh7Pmh8YNPXOtYQTDD4JnKZE4ozYc4HJtNvDBnCc61MGFgq4NipAwnq/mFTKNa3k+dLWCL7pAfKAHJfWkJ/vjAuh0iDaT2ITmGlPHDX6iPrvXsyNYVf4YyivpTnRLvT1ZHFBIz60A+wJNB7F/9HCm1MvTtv5k1RCkFYteeQZpqeoqU/4W9oMJI1AEAkKiHfKWFqZ29zbs2NsWMdkZV07e6nrthEkXufZfeVzFQK+8N0MRAW2DP+5/AftKwqoN1GqlkmrqBFM2264IAuckqGVLwS6nzL67kQC5MOy90REX5iOE+QlZ5AoDNbTHXCztWKpW4qZtuU6GlhuJRROcPi22TxEIBds+t6GajkDep5ZRSvysEcTcaRDSW9FJYmxihX1ODQgau8/fm86yagldN4vkKhUiKDZ1M+0/Rh1wTxn4BhcgXYnFk/GvPyG+JvlINt9U5oNqFDD4UtvV30Bob2yxFCO3XnC+Bq4Rz8G0N7wySlKvTzI7wsu7aa8mq4cPc=
  on:
     tags: true
     branch: master

