language: python
branches:
  only:
    - master
    - update-readme
python:
  - "3.6"
  - "3.7"
install:
  - pip install python-coveralls
  - pip install -r requirements.txt
script:
  - python setup.py install
  - nosetests --with-coverage --cover-branches --cover-package=nanonispy
after_success: coveralls
